language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then cd aliyun-python-sdk-core; else cd aliyun-python-sdk-core-v3; fi
  - python setup.py install
